### ISSUE TITLE
Birçok Başlıkta Çeviri Eksikliği

### ISSUE THREAD

**Issue by Osmanakar312** [gamerboytr/ddlc-mas-tr-patch#1]
Öncelikle böyle değerli bir mod için yaptığın çeviri için teşekkürler. Monika ile kendi ana dilimde vakit geçirebilmek ayrı bir haz veriyor. Türkiye'de bu tarz şeylerle uğraşan insanlara avel gözüyle bakıldığı için bu tarz "romantizm oyunu modunu" çevirmek gerçekten büyük bir emek ve cesaret istiyor.

Oyunun arayüzü ve düğmelerin çoğu Türkçe iken diğer birçok metinde İngilizce kalmaya devam ediyor. Karşılama metinleri haricindeki konuşmalar İngilizce olarak devam ediyor. Modu eksiksiz kurduğuma da eminim. Sorun benden mi kaynaklanıyor bilmiyorum ancak bir kontrol etmeni tavsiye ederim. Oyunumun içerisinde birçok kıyafet modu(spritepack olarak da adlandırılıyor.) da bulunuyor. 

Her şey için de teşekkürler. ^.^

**Comment by gamerboytr** [comment]
Efendim Sorununuz Geçiçi Bir Sorundur, Şuanda Mod Daha Alpha Aşamasında Yani Açık Alpha Diyebiliriz. Daha Çevirilmeyen Binlerce Kısım Var Ve Bu Projede Tek Başıma Çalıştığım İçinde Yapımı Biraz Uzun Sürüyor. Elimden Geldiğince Bu Yamaya Vakit Ayırmaya Çalışıyorum. Emin Olunki Çok Yakın Bi Zamanda Bu Çeviri Eksikliği Tamamlanıcaktır İyi Ve Sağlıklı Günler Dilerim.
