### ISSUE TITLE
çeviri hatası

### ISSUE THREAD

**Issue by 0Swift** [gamerboytr/ddlc-mas-tr-patch#8]
oyunu hangi sürümde oynamalıyım çoğu şey çevirilmemiş

**Comment by gamerboytr** [comment]
Efendim oyunun indirme bölümünde o kadar yapım aşamasında olarak bildirmeme rağmen bunu demeniz biraz ironik açıkçası. Yamanın en son sürümü 0.12.7 sürümüne uyarlanmıştır. İyi günler dilerim
